# Generated by Django 4.2.2 on 2023-08-05 20:31

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_assigment_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigment', to='core.assigment')),
            ],
        ),
    ]
