# Generated by Django 4.2.2 on 2023-08-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_studentsassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsassignment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='students_assigments'),
        ),
    ]
