# Generated by Django 4.2.2 on 2023-08-01 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_lessons_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='section',
            field=models.ManyToManyField(default=None, related_name='section_of_lesson', to='staff.sections'),
        ),
    ]
