# Generated by Django 4.2.2 on 2023-06-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseuser', '0002_student_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='birthday',
            new_name='birthdate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='grade',
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin')], max_length=500),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
