# Generated by Django 4.2.2 on 2023-06-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseuser', '0004_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='static/images/profile.png', upload_to='profile_photos'),
        ),
    ]
