# Generated by Django 4.2.2 on 2023-07-15 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0013_remove_student_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='staff.lesson')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='staff.student')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='staff.teacher')),
            ],
            options={
                'verbose_name_plural': 'Class',
            },
        ),
    ]
