# Generated by Django 4.2.2 on 2023-07-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_remove_teacher_students'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classname',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='classname',
            name='student',
        ),
        migrations.RemoveField(
            model_name='classname',
            name='teacher',
        ),
        migrations.AddField(
            model_name='classname',
            name='lesson',
            field=models.ManyToManyField(to='staff.lesson'),
        ),
        migrations.AddField(
            model_name='classname',
            name='student',
            field=models.ManyToManyField(to='staff.student'),
        ),
        migrations.AddField(
            model_name='classname',
            name='teacher',
            field=models.ManyToManyField(to='staff.teacher'),
        ),
    ]
