# Generated by Django 4.2.2 on 2023-07-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_sections_teacher'),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='student',
            field=models.ManyToManyField(null=True, related_name='class_of_students', to='staff.students'),
        ),
    ]
