# Generated by Django 4.2.2 on 2023-07-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_remove_teacher_students'),
        ('core', '0002_remove_classname_lesson_remove_classname_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classname',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='classname',
            name='student',
        ),
        migrations.RemoveField(
            model_name='classname',
            name='teacher',
        ),
        migrations.AddField(
            model_name='classname',
            name='lessons',
            field=models.ManyToManyField(to='staff.lesson'),
        ),
        migrations.AddField(
            model_name='classname',
            name='students',
            field=models.ManyToManyField(to='staff.student'),
        ),
        migrations.AddField(
            model_name='classname',
            name='teachers',
            field=models.ManyToManyField(to='staff.teacher'),
        ),
    ]
