# Generated by Django 4.2.2 on 2023-07-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_remove_teacher_students'),
        ('core', '0003_remove_classname_lesson_remove_classname_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classname',
            name='students',
            field=models.ManyToManyField(related_name='student_of_class', to='staff.student'),
        ),
    ]
