# Generated by Django 4.2.2 on 2023-07-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_classname_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='classname',
            name='maximum_student',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
