# Generated by Django 4.2.2 on 2023-07-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0019_remove_lesson_teacher_lesson_teacher'),
        ('core', '0006_remove_classname_lessons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classname',
            name='teachers',
        ),
        migrations.AddField(
            model_name='classname',
            name='lessons',
            field=models.ManyToManyField(related_name='lesson_of_class', to='staff.lesson'),
        ),
    ]
