# Generated by Django 4.2.2 on 2023-08-05 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_alter_lessons_section'),
        ('core', '0006_assigment_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigment',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_of_assignment', to='staff.lessons'),
        ),
    ]
