# Generated by Django 4.2.2 on 2023-07-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0021_remove_lesson_teacher_lesson_teacher'),
        ('core', '0007_remove_classname_teachers_classname_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='classname',
            name='teachers',
            field=models.ManyToManyField(related_name='teacher_of_class', to='staff.teacher'),
        ),
    ]
