# Generated by Django 4.2.2 on 2023-08-05 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_studentsassignment_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentsassignment',
            options={'verbose_name_plural': 'Students Assignment'},
        ),
        migrations.RemoveField(
            model_name='assigment',
            name='receiver',
        ),
    ]
