# Generated by Django 4.2.2 on 2023-07-20 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0021_remove_lesson_teacher_lesson_teacher'),
        ('core', '0009_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classname',
            name='maximum_student',
        ),
        migrations.AlterField(
            model_name='classname',
            name='students',
            field=models.ManyToManyField(related_name='student_of_class', to='staff.student', validators=[django.core.validators.MaxValueValidator(30)]),
        ),
    ]
