# Generated by Django 4.2.2 on 2023-08-05 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_alter_lessons_section'),
        ('core', '0010_alter_studentsassignment_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assigment',
            new_name='Assignment',
        ),
    ]
