# Generated by Django 4.2.2 on 2023-07-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0021_remove_lesson_teacher_lesson_teacher'),
        ('core', '0010_remove_classname_maximum_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classname',
            name='students',
            field=models.ManyToManyField(related_name='student_of_class', to='staff.student'),
        ),
    ]
