# Generated by Django 4.2.2 on 2023-08-06 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_rename_assigment_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigment_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
