# Generated by Django 4.2.2 on 2023-08-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_alter_lessons_section'),
        ('core', '0012_alter_assignment_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='receiver',
            field=models.ManyToManyField(blank=True, related_name='assignment_receivers', to='staff.sections'),
        ),
    ]
