# Generated by Django 4.2.2 on 2023-08-06 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_assignment_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsassignment',
            name='attempts',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
