# Generated by Django 4.2.2 on 2023-07-01 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_remove_lesson_teacher_lesson_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_role', to='staff.lesson'),
        ),
    ]
