# Generated by Django 4.2.2 on 2023-08-01 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_sections_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sections',
            name='max_student_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sections',
            name='students',
            field=models.ManyToManyField(related_name='students_of_section', to='staff.students'),
        ),
    ]
