# Generated by Django 4.2.2 on 2023-08-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_sections_max_student_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='section',
            field=models.ManyToManyField(related_name='section_of_lesson', to='staff.sections'),
        ),
    ]
