# Generated by Django 4.2.2 on 2023-07-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_remove_lesson_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(max_length=232),
        ),
    ]
