# Generated by Django 4.2.2 on 2023-07-02 15:03

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_alter_student_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='lessons',
            field=models.ManyToManyField(related_name='students', to='staff.lesson'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='about_teacher',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='students',
            field=models.ManyToManyField(related_name='students', to='staff.student'),
        ),
    ]
