# Generated by Django 4.2.2 on 2023-07-02 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_student_lessons_teacher_about_teacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='description',
        ),
    ]
