# Generated by Django 4.2.2 on 2023-07-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_remove_lesson_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_role',
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ManyToManyField(related_name='teacher_of_lesson', to='staff.teacher'),
        ),
    ]
