# Generated by Django 4.2.2 on 2023-07-15 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_remove_student_lessons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='students',
        ),
    ]
