# Generated by Django 4.2.2 on 2023-07-16 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_classname_teachers_classname_lessons'),
        ('staff', '0019_remove_lesson_teacher_lesson_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.classname'),
        ),
    ]
